# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ec0ecd2b8829f7c4cc7e68d418bd39a9813a48e175cff3711865f71ef15463bf5c12e3db2217ee335717c8e5144039b12832c017b9ea093e36c45ff6ae4df64f

test:
  secret_key_base: 5e9c3d729539f1dd233940426ba24b5a2ef4665536e7a30ebd145eca2e6956db24eb64232768ab58c60b40370fe6cee627a5e608980b69ceb2b49f52eeae720b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
